try {
    const val1 = 1
    val1 = 2

}catch (e) {
    console.log("Hi rapaz")
}




// const x = 10;
// try {
//   x = 2;
// } catch (err) {
//   console.log(`Erro: ${err}`);
// }